[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''let g:rainbow_active = 1'''

# syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'wavded/vim-stylus'

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'mattn/emmet-vim'
