[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'sgur/ctrlp-memolist.vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
on_ft = ['typescript', 'vue']

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'cespare/vim-toml'

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
